openapi: "3.0.0"
info:
  version: 1.0.0
  title: Book store

servers:
  - url: http://localhost:8080

paths:
  /books-order:
    post:
      summary: Create book order
      operationId: create book order
      tags:
        - book-order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookOrder'
      responses:
        201:
          description: Order created
components:
  schemas:
    BookOrder:
      type: object
      properties:
        title:
          type: string
        isbn:
          type: string
        userEmail:
          type: string
        deliveryAddress:
          type: string