openapi: "3.0.0"
info:
  version: 1.0.0
  title: Book store

servers:
  - url: http://localhost:8080

paths:
  /order:
    post:
      summary: Create send order
      operationId: createSendOrder
      tags:
        - order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        201:
          description: Order created
components:
  schemas:
    Order:
      type: object
      properties:
        email:
          type: string
        deliveryAddress:
          type: string